version: '3.8'

services:
  # Development database
  postgres:
    image: postgres:16-alpine
    container_name: savoir-link-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d savoir_link_dev"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:
